package com.example.demo.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Billinfo generated by hbm2java
 */
@Entity
@Table(name = "billinfo")
public class Billinfo implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCart", nullable = false)
	private Cart cart;
	
	@Column(name = "totalPrice", nullable = false, precision = 12, scale = 0)
	private Float totalPrice;
	
	@Column(name = "shippingAddress", nullable = false, length = 200)
	private String shippingAddress;
	
	@Column(name = "recipientName", nullable = false, length = 200)
	private String recipientName;
	
	@Column(name = "recipientPhone", nullable = false, length = 200)
	private String recipientPhone;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datePayment", length = 19)
	private Date datePayment;
	
	@Column(name = "status", nullable = false)
	private int status;

	public Billinfo() {
	}

	public Billinfo(Cart cart, float totalPrice, String shippingAddress, String recipientName, String recipientPhone, int status) {
		this.cart = cart;
		this.totalPrice = totalPrice;
		this.shippingAddress = shippingAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.status = status;
	}

	public Billinfo(Cart cart,  float totalPrice,
			String shippingAddress, String recipientName, String recipientPhone, Date datePayment, int status) {
		this.cart = cart;
		this.totalPrice = totalPrice;
		this.shippingAddress = shippingAddress;
		this.recipientName = recipientName;
		this.recipientPhone = recipientPhone;
		this.datePayment = datePayment;
		this.status = status;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}
	
	public float getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(float totalPrice) {
		this.totalPrice = totalPrice;
	}

	
	public String getShippingAddress() {
		return this.shippingAddress;
	}

	public void setShippingAddress(String shippingAddress) {
		this.shippingAddress = shippingAddress;
	}

	
	public String getRecipientName() {
		return this.recipientName;
	}

	public void setRecipientName(String recipientName) {
		this.recipientName = recipientName;
	}

	
	public String getRecipientPhone() {
		return this.recipientPhone;
	}

	public void setRecipientPhone(String recipientPhone) {
		this.recipientPhone = recipientPhone;
	}

	
	public Date getDatePayment() {
		return this.datePayment;
	}

	public void setDatePayment(Date datePayment) {
		this.datePayment = datePayment;
	}

	
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
